# Telegram Bot Configuration
telegram:
  # Get your bot token from @BotFather (https://t.me/BotFather)
  token: "YOUR_BOT_TOKEN_HERE"
  # Maximum voice message duration in seconds (20 minutes = 1200 seconds)
  max_voice_duration: 1200

# Paths Configuration
paths:
  # Directory for temporary files (will be created if not exists)
  temp_dir: "temp"
  # Path to Python speech recognition script
  python_script: "src/python/speech_recognition.py"
  # Path to FFmpeg executable (required for audio conversion)
  ffmpeg: "bin/ffmpeg/bin/ffmpeg.exe"

# Speech Recognition Configuration
speech:
  # Whisper model size options: tiny, base, small, medium, large
  # Larger models are more accurate but require more GPU memory and processing time
  model: "medium"
  # Default language for recognition
  default_language: "ru"
  # Supported languages and their codes
  languages:
    ru: "Russian"
    en: "English"
    uk: "Ukrainian"
    be: "Belarusian"
  # Set to true if you have NVIDIA GPU with CUDA support
  use_gpu: true
  # Enable automatic language detection (may increase processing time)
  auto_detect_language: false

# Audio Configuration
audio:
  # Audio sample rate in Hz (16kHz is optimal for Whisper)
  sample_rate: 16000
  # Number of audio channels (1 = mono)
  channels: 1
  # Bit depth for WAV files
  bit_depth: 16
